mvc/2/Models/ErrorViewModel.cs
namespace _2.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

mvc/2/Models/StudentModel.cs
namespace _2.Models;

public class Student
{
    public ulong? Id { get; set; }

    public required string Name { get; set; }

    public required double Score { get; set; }
}

mvc/2/Controllers/AptechController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _2.Models;

namespace _2.Controllers;

public class AptechController : Controller
{
    private readonly ILogger<AptechController> _logger;

    private readonly List<Student> Students = [
        new Student {
            Id = 1,
            Name = "John Doe",
            Score = 90,
        },
        new Student {
            Id = 2,
            Name = "Jane Doe",
            Score = 80,
        },
        new Student {
            Id = 3,
            Name = "Foo",
            Score = 85,
        },
        new Student {
            Id = 4,
            Name = "Bar",
            Score = 95,
        },
    ];

    public AptechController(ILogger<AptechController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Student(ulong? id)
    {
        if (id == null)
        {
            return View(Students);
        }
        else
        {
            Student? student = Students.FirstOrDefault(x => x.Id == id.Value);
            if (student == null) return NotFound();
            return View(model: student, viewName: "StudentDetails");
        }
        
    }
}

mvc/2/Controllers/VietnamController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _2.Models;

namespace _2.Controllers;

public class VietnamController : Controller
{
    private readonly ILogger<VietnamController> _logger;

    private readonly List<string> CityList = [
        "Cao Bằng",
        "Lạng Sơn",
        "Phú Thọ",
        "Quảng Ninh",
        "Thái Nguyên",
        "Tuyên Quang",
        "Lào Cai",
        "Điện Biên",
        "Lai Châu",
        "Sơn La",
        "Bắc Ninh",
        "Hưng Yên",
        "Ninh Bình",
        "Hà Nội",
        "Hải Phòng",
        "Hà Tĩnh",
        "Nghệ An",
        "Quảng Trị",
        "Thanh Hóa",
        "Huế",
        "Đắk Lắk",
        "Gia Lai",
        "Lâm Đồng",
        "Khánh Hòa",
        "Quảng Ngãi",
        "Da Nang",
        "Đồng Nai",
        "Tây Ninh",
        "Hồ Chí Minh",
        "An Giang",
        "Cà Mau",
        "Đồng Tháp",
        "Vĩnh Long",
        "Cần Thơ",
    ];

    public VietnamController(ILogger<VietnamController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Cities()
    {
        return View(CityList);
    }
}

mvc/2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aptech" asp-action="Index">Aptech</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vietnam" asp-action="Index">Vietnam</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - _2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

mvc/2/Views/Vietnam/Cities.cshtml
@model List<string>
@{
    ViewData["Title"] = "Cities";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <tr>
        <th>No.</th>
        <th>Name</th>
    </tr>
    @for (int a = 0; a < Model.Count; a++) {
        <tr>
            <td>@(a + 1)</td>
            <td>@Model[a]</td>
        </tr>
    }
</table>

mvc/2/Views/Vietnam/Index.cshtml

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Vietnam</h1>
</div>

<p class="text-center">
    <a asp-controller="Vietnam" asp-action="Cities">All Cities</a>
</p>